export const RestroData = [
  {
    id: "the-gramercy-tavern-burger-4-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/137148/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Gramercy Tavern",
    dsc: "The Gramercy Tavern Burger - 4 Pack",
    price: 99,
    rate: 5,
    country: "New York, NY",
  },
  {
    id: "6-lou-malnatis-deep-dish-pizzas",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/106829/6-lou-malnatis-deep-dish-pizzas.f59993181da5d295668c8a6fb856055e.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Lou Malnati's Pizza",
    dsc: "6 Lou Malnati's Deep Dish Pizzas",
    price: 116.99,
    rate: 4,
    country: "Chicago, IL",
  },
  {
    id: "corn-cheese-bread-2-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/133923/corn-cheese-bread-2-pack.703937ce3943d6caad78d3612cd9dcef.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Calic Bread",
    dsc: "Corn Cheese Bread - 2 Pack",
    price: 89,
    rate: 5,
    country: "Los Angeles, CA",
  },
  {
    id: "pork-steaks",
    img: "https://goldbelly.imgix.net/uploads/product_image/image/41969/pork-steaks.aaa962e22c9099952fdf15cb0382bd65.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Southside Market & Barbeque",
    dsc: "Pork Steaks",
    price: 69,
    rate: 5,
    country: "Elgin, TX",
  },
  {
    id: "15259-german-chocolate-killer-brownie-tin-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/132029/german-chocolate-killer-brownie-tin-pack.5ebc34160f28767a9d94c4da2e04c4b9.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Killer Brownie®",
    dsc: "German Chocolate Killer Brownie®",
    price: 39.99,
    rate: 4,
    country: "Dayton, OH",
  },
  {
    id: "hot-chicken-whole-bird",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/110733/hot-chicken-whole-bird.bfd696b1cf611210ee813293c4c1bf28.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Hattie B's Hot Chicken",
    dsc: "Hot Chicken - Whole Bird",
    price: 89,
    rate: 5,
    country: "Nashville, TN",
  },
];
